### ISSUE TITLE
Restructure Codebase

### ISSUE THREAD

**Issue by cedric-h** [StevenCopeland/FILEPLAN#35]
A few loops here and there couldn't hurt anybody, could they? Please try to avoid repetitive cut and pastes, they make me cry inside. I'll cut out all of the repetitive parts of the code and replace them with clean, elegant loops.

**Comment by StevenCopeland** [comment]
@DefecateRainbows  What do you think now?

**Comment by sparkle-sparkle** [comment]
Can I help? Is this still an open issue?

**Comment by StevenCopeland** [comment]
If you can find something you can minify then yes you can help.

**Comment by sparkle-sparkle** [comment]
when you say minify, do you mean refactoring the code?

**Comment by StevenCopeland** [comment]
Yes

**Comment by sparkle-sparkle** [comment]
Okay, I'll have a go at it 😊

**Comment by StevenCopeland** [comment]
Good luck!

**Comment by sparkle-sparkle** [comment]
Thnx! 😊

**Comment by StevenCopeland** [comment]
@sparkle-sparkle I merged your PR to soon. Please fix the bugs in the code.

**Comment by sparkle-sparkle** [comment]
Will do.

**Comment by DefecateRainbows** [comment]
Still working on this. It's going to glisten when I'm done with it.

**Comment by StevenCopeland** [comment]
I hope so!!!

**Comment by DefecateRainbows** [comment]
Alright, I've done a lot of refactoring. Git says I rewrote 70% of the html and 90% of script. I also made some images while I was there, because I'm pretty sure Bill Gates doesn't much appreciate us stealing images from Windows, like you were doing with your screenshots. There are now master classes for each kind of upgrade, the code's pretty readable but if you have any questions, lemme know. I made the images in Inkscape.

**Comment by DefecateRainbows** [comment]
I'll leave it open until you merge my pull request, because it's not really fixed until then.
Basically, the way that I set up the code base is like this:
If you want to add, for example, a clicker upgrade, you can do so with code like this:
